In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
print("Array created: ", arr1)
# np.save("/data/input/task_02_arr1", arr1)

Array created:  [1 2 3 4]


In [3]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [1,2,9,0]])
print("Array Created: \n", arr2)

Array Created: 
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 9 0]]


In [4]:
arr3 = np.array([[[1,1], [2,2], [3,3], [4,4]],
                 [[4,4], [5,5], [6,6], [7,7]],
                 [[7,7], [8,8], [9,9], [0,0]]])
print("Array Created: \n", arr3)

Array Created: 
 [[[1 1]
  [2 2]
  [3 3]
  [4 4]]

 [[4 4]
  [5 5]
  [6 6]
  [7 7]]

 [[7 7]
  [8 8]
  [9 9]
  [0 0]]]


In [5]:
print("Size or arr3 is: \n", arr3.size)
print("Shape or arr3 is: \n", arr3.shape)
print("Dimention or arr3 is: \n", arr3.ndim)
print("Itemsize or arr3 is: \n", arr3.itemsize)


Size or arr3 is: 
 24
Shape or arr3 is: 
 (3, 4, 2)
Dimention or arr3 is: 
 3
Itemsize or arr3 is: 
 8


In [7]:
print("Array Created By Arange Function is: \n", np.arange(0,1,0.1))
print("Array Created By Linspace Function is: \n", np.linspace(0,1,12))
print("Array Created By Logspace Function is: \n", np.logspace(0,2,20))
print("Array Created By Zeros Function is: \n", np.zeros((2,3)))
print("Array Created By Eye Function is: \n", np.eye(3))
print("Array Created By Diag Function is: \n", np.diag([1,2,3,4]))
# np.save("/data/input/task_02_diag", np.diag([1,2,3,4]))

Array Created By Arange Function is: 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
Array Created By Linspace Function is: 
 [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]
Array Created By Logspace Function is: 
 [  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]
Array Created By Zeros Function is: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Array Created By Eye Function is: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array Created By Diag Function is: 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [8]:
arr4 = np.arange(10)
print("Index Value is: \n", arr4[5])
print("Index Value is: \n", arr4[3:5])
print("Index Value is: \n", arr4[:5])
print("Index Value is: \n", arr4[-1])

Index Value is: 
 5
Index Value is: 
 [3 4]
Index Value is: 
 [0 1 2 3 4]
Index Value is: 
 9


In [9]:
arr5 = np.array([[1,2,3,4,5], [4,5,6,7,8], [7,8,9,0,1]])
print("Two-Dimentional Array is: \n", arr5)
print("Index Value Is : \n", arr5[0,3:5])
print("Index Value Is : \n", arr5[1:,2:])
print("Index Value Is : \n", arr5[:,2])

Two-Dimentional Array is: 
 [[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 0 1]]
Index Value Is : 
 [4 5]
Index Value Is : 
 [[6 7 8]
 [9 0 1]]
Index Value Is : 
 [3 6 9]


In [10]:
arr6 = np.array([[1,-2,9,6], [-9,-5,-3,-1], [1,4,-9,-5]])
print(np.all(arr6))

True


In [11]:
arr7 = np.array([[1,0,0,0,0], [0,0,0,0,0], [0,0,0,0,0]])
print(np.any(arr7))
print(np.all(arr7))

True
False


In [12]:
arr8 = np.array([[1,2,3,4,5], [3,4,5,6,7]])
arr9 = np.where(arr8>3)
# np.save("/data/input/task_02_arr9", arr9)
print(arr9)

(array([0, 0, 1, 1, 1, 1]), array([3, 4, 1, 2, 3, 4]))
