In [ ]:
# Import NumPy
import numpy as np

In [ ]:
# Array Having 10 Zeros
ar1 = np.zeros(10)
ar1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Array on 10 Ones
ar0 = np.ones(10)
ar0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Converting 1D Array Into 2D Array
ar2 = np.arange(1,13)
print("1-D Array: ", ar2)
ar3 = ar2.reshape(3,4)
print("2D Array: ", ar3)

1-D Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Finding Maximum And Minimum in Array
print("Minimum is: ", ar2.min())
print("Maximum is: ", ar2.max())

Minimum is:  1
Maximum is:  12


In [ ]:
# Finding Mean
ar2.mean()

np.float64(6.5)

In [ ]:
# Finding Median
ar4 = np.median(ar2)
ar4

np.float64(6.5)

In [ ]:
# Finding Standard Deviation
ar5 = np.std(ar2)
ar5

np.float64(3.452052529534663)

In [ ]:
# Identity Matrix of Size 3x3
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])