In [ ]:
# Import NumPy
import numpy as np

In [ ]:
# Array Having 10 Zeros
ar1 = np.zeros(10)
ar1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Array on 10 Ones
ar0 = np.ones(10)
ar0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Converting 1D Array Into 2D Array
ar2 = np.arange(1,13)
print("1-D Array: ", ar2)
ar3 = ar2.reshape(3,4)
print("2D Array: ", ar3)

1-D Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Finding Maximum And Minimum in Array
print("Minimum is: ", ar2.min())
print("Maximum is: ", ar2.max())

Minimum is:  1
Maximum is:  12


In [ ]:
# Finding Mean
ar2.mean()

np.float64(6.5)

In [ ]:
# Finding Median
ar4 = np.median(ar2)
ar4

np.float64(6.5)

In [ ]:
# Finding Standard Deviation
ar5 = np.std(ar2)
ar5

np.float64(3.452052529534663)

In [ ]:
# Identity Matrix of Size 3x3
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Replace All Negative Numbers In Array With 0
ar6 = np.array([1, -9, 6, -2, -7, 8, -4])
ar6[ar6 < 0] = 0
ar6

array([1, 0, 6, 0, 0, 8, 0])

In [ ]:
# Filter All Elements Graeter Than 20
ar7 = np.array([7, 9, 21, 13, 43, 88, 90, 54, 24, 9, 1, 0])
ar8 = ar7[ar7 > 20]
ar8

array([21, 43, 88, 90, 54, 24])

In [33]:
# Add And Multiply Two Arrays Element Wise
ar9 = np.arange(1,20,2)
ar10 = np.arange(21,40,2)
print("Sum Is: ", np.add(ar9,ar10))
print("Product Is: ", np.multiply(ar9,ar10))

Sum Is:  [22 26 30 34 38 42 46 50 54 58]
Product Is:  [ 21  69 125 189 261 341 429 525 629 741]


In [ ]:
# Concatenate 2 Arrays Vertically
ar11 = np.array([[1,2,3,4,5], [9,8,7,6,5]])
ar12 = np.array([[1,7,9,2,5], [3,8,4,6,5]])
ar13 = np.concatenate((ar11,ar12), axis = 1)
ar13

array([[1, 2, 3, 4, 5, 1, 7, 9, 2, 5],
       [9, 8, 7, 6, 5, 3, 8, 4, 6, 5]])