In [2]:
import numpy as np

In [ ]:
arr_0 = 43
arr_0

43

In [ ]:
arr_1 = [0,1,2,3,4,5,6,7,8,9]
arr_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
arr_1d = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
type(arr_1d)

numpy.ndarray

In [16]:
arr_1d.shape

(10,)

In [17]:
arr_1d.size

10

In [19]:
print(type(arr_1d))

<class 'numpy.ndarray'>


In [20]:
arr_1d.ndim

1

In [23]:
arr_1d.dtype

dtype('int64')

In [26]:
arr_2d = np.array([[0,1,2,3],
                   [4,5,6,7]])
print(arr_2d)

[[0 1 2 3]
 [4 5 6 7]]


In [36]:
print(type(arr_2d))
print(arr_2d.ndim)
print(arr_2d.size)
print(arr_2d.shape)
print(arr_2d.dtype)

<class 'numpy.ndarray'>
2
8
(2, 4)
int64


In [34]:
mx1s = np.array([[1,1,1,1,1],
                 [1,1,1,1,1],
                 [1,1,1,1,1]])
print(mx1s)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [35]:
print(type(mx1s))
print(mx1s.ndim)
print(mx1s.size)
print(mx1s.shape)
print(mx1s.dtype)

<class 'numpy.ndarray'>
2
15
(3, 5)
int64


In [43]:
mx1ds = np.ones(9)
print(mx1ds)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [44]:
print(type(mx1ds))
print(mx1ds.ndim)
print(mx1ds.size)
print(mx1ds.shape)
print(mx1ds.dtype)

<class 'numpy.ndarray'>
1
9
(9,)
float64


In [46]:
mx2ds = np.ones((2,5))
print(mx2ds)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
print(type(mx2ds))
print(mx2ds.ndim)
print(mx2ds.size)
print(mx2ds.shape)
print(mx2ds.dtype)

<class 'numpy.ndarray'>
2
10
(2, 5)
float64


In [52]:
mx1dds = np.ones((3,4), dtype = int)
print(mx1dds)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [53]:
print(type(mx1dds))
print(mx1dds.ndim)
print(mx1dds.size)
print(mx1dds.shape)
print(mx1dds.dtype)

<class 'numpy.ndarray'>
2
12
(3, 4)
int64


In [3]:
mx0s = np.zeros(5)
print (mx0s)

[0. 0. 0. 0. 0.]


In [5]:
print(type(mx0s))
print(mx0s.ndim)
print(mx0s.size)
print(mx0s.shape)
print(mx0s.dtype)

<class 'numpy.ndarray'>
1
5
(5,)
float64


In [4]:
mx0ss = np.zeros((3,4))
print(mx0ss)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
print(type(mx0ss))
print(mx0ss.ndim)
print(mx0ss.size)
print(mx0ss.shape)
print(mx0ss.dtype)

<class 'numpy.ndarray'>
2
12
(3, 4)
float64


In [7]:
mx0sb = np.zeros((4,3) , dtype = bool)
print(mx0sb)

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [10]:
mx0sss = np.zeros((4,3) , dtype = str)
print(mx0sss)

[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]


In [12]:
em_str = ''
print(bool(em_str))

False


In [14]:
arr_11 = np.arange(1,20)
print(arr_11)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
arr_11.size

19

In [37]:
arr_12 = np.arange(1,24,2)
print(arr_12)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [38]:
np.linspace(1,6,8)

array([1.        , 1.71428571, 2.42857143, 3.14285714, 3.85714286,
       4.57142857, 5.28571429, 6.        ])

In [40]:
arr_21 = arr_12.reshape(3,4)
print(arr_21)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [42]:
arr_31 = arr_21.reshape(2,3,2)
print(arr_31)

[[[ 1  3]
  [ 5  7]
  [ 9 11]]

 [[13 15]
  [17 19]
  [21 23]]]


In [43]:
ar = np.arange(1,25).reshape(3,8)
ar

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [46]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [47]:
ar.transpose()

array([[ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23],
       [ 8, 16, 24]])

In [48]:
ar_1 = np.arange(1,17).reshape(4,4)
ar_2 = np.arange(1,17).reshape(4,4)
print(ar_1)
print(ar_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [49]:
ar_1 + ar_2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [50]:
np.add(ar_1,ar_2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [51]:
ar_1 - ar_2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [52]:
np.subtract(ar_1,ar_2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [53]:
ar_1/ar_2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.divide(ar_1,ar_2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
ar_1 * ar_2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [56]:
np.multiply(ar_1,ar_2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [57]:
ar_1 @ar_2

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [58]:
ar_1.dot(ar_2)

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [59]:
ar_3 = np.arange(1,13).reshape(4,3)
print(ar_3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [60]:
np.max(ar_3)

np.int64(12)

In [61]:
np.min(ar_3)

np.int64(1)