In [1]:
import numpy as np

In [3]:
ar = np.arange(1,101).reshape(10,10)
print(ar)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [5]:
print(ar[8,5])

86


In [6]:
print(ar[5,7].ndim)

0


In [7]:
ar[7]

array([71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [8]:
ar[: ,3]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [9]:
ar[: ,3].ndim

1

In [10]:
ar[: , 1:4]

array([[ 2,  3,  4],
       [12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [11]:
ar[: , 1:4].ndim

2

In [22]:
ar[1:6, 1:6]

array([[12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46],
       [52, 53, 54, 55, 56]])

In [23]:
ar[:, 2:6]

array([[ 3,  4,  5,  6],
       [13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36],
       [43, 44, 45, 46],
       [53, 54, 55, 56],
       [63, 64, 65, 66],
       [73, 74, 75, 76],
       [83, 84, 85, 86],
       [93, 94, 95, 96]])

In [24]:
ar[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [25]:
ar[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [26]:
ar[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
ar_1 = np.arange(1,26).reshape(5,5)
print(ar_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
ar_2 = np.arange(26,51).reshape(5,5)
print(ar_2)

[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [30]:
li_1 = [1,2,3,4,5]
li_2 = [5,4,3,2,1]

In [31]:
li_1 + li_2

[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]

In [32]:
ar_1 + ar_2

array([[27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45],
       [47, 49, 51, 53, 55],
       [57, 59, 61, 63, 65],
       [67, 69, 71, 73, 75]])

In [34]:
np.concatenate((ar_1,ar_2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [35]:
print(ar_1)
print(ar_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [36]:
np.concatenate((ar_1,ar_2), axis = 1)

array([[ 1,  2,  3,  4,  5, 26, 27, 28, 29, 30],
       [ 6,  7,  8,  9, 10, 31, 32, 33, 34, 35],
       [11, 12, 13, 14, 15, 36, 37, 38, 39, 40],
       [16, 17, 18, 19, 20, 41, 42, 43, 44, 45],
       [21, 22, 23, 24, 25, 46, 47, 48, 49, 50]])

In [37]:
np.hstack((ar_1,ar_2))

array([[ 1,  2,  3,  4,  5, 26, 27, 28, 29, 30],
       [ 6,  7,  8,  9, 10, 31, 32, 33, 34, 35],
       [11, 12, 13, 14, 15, 36, 37, 38, 39, 40],
       [16, 17, 18, 19, 20, 41, 42, 43, 44, 45],
       [21, 22, 23, 24, 25, 46, 47, 48, 49, 50]])

In [39]:
np.hstack((ar_1,ar_2,ar_2))

array([[ 1,  2,  3,  4,  5, 26, 27, 28, 29, 30, 26, 27, 28, 29, 30],
       [ 6,  7,  8,  9, 10, 31, 32, 33, 34, 35, 31, 32, 33, 34, 35],
       [11, 12, 13, 14, 15, 36, 37, 38, 39, 40, 36, 37, 38, 39, 40],
       [16, 17, 18, 19, 20, 41, 42, 43, 44, 45, 41, 42, 43, 44, 45],
       [21, 22, 23, 24, 25, 46, 47, 48, 49, 50, 46, 47, 48, 49, 50]])

In [41]:
np.split(ar_1,5)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20]]),
 array([[21, 22, 23, 24, 25]])]

In [42]:
ls_1 = np.split(ar_2 , 5)

In [43]:
type(np.split(ar_2 , 5))

list

In [53]:
ls_1[1]

array([[31, 32, 33, 34, 35]])

In [54]:
type(ls_1[1])

numpy.ndarray

In [59]:
np.split(ar_1, 5 , axis = 1)

[array([[ 1],
        [ 6],
        [11],
        [16],
        [21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]]),
 array([[ 5],
        [10],
        [15],
        [20],
        [25]])]

In [8]:
np.random.random(1)

array([0.2193793])

In [13]:
np.random.random((5,5))

array([[0.95691995, 0.09151586, 0.35192373, 0.82848498, 0.42003334],
       [0.58155639, 0.66439921, 0.96122355, 0.05167731, 0.76410325],
       [0.42418973, 0.75466931, 0.92806915, 0.40121827, 0.34662745],
       [0.96860678, 0.49679692, 0.1089525 , 0.98482754, 0.49004364],
       [0.92676957, 0.94506002, 0.03866553, 0.39828923, 0.28134978]])

In [16]:
np.random.randint(1,9 , (5,5))

array([[8, 2, 5, 1, 8],
       [5, 6, 7, 3, 6],
       [1, 4, 4, 2, 4],
       [2, 2, 1, 6, 4],
       [3, 6, 1, 5, 8]], dtype=int32)

In [65]:
np.random.randint(1,9 , (5,5,5))

array([[[6, 8, 5, 2, 7],
        [3, 3, 5, 7, 1],
        [7, 5, 3, 6, 4],
        [6, 7, 6, 5, 2],
        [7, 2, 7, 3, 5]],

       [[1, 7, 5, 3, 2],
        [1, 1, 3, 4, 7],
        [6, 1, 7, 5, 5],
        [7, 6, 8, 1, 6],
        [1, 7, 3, 5, 8]],

       [[2, 8, 3, 2, 8],
        [3, 8, 5, 2, 2],
        [4, 3, 3, 7, 8],
        [6, 2, 6, 3, 4],
        [3, 2, 8, 5, 7]],

       [[1, 3, 6, 1, 1],
        [5, 8, 5, 2, 7],
        [4, 5, 7, 1, 6],
        [7, 5, 5, 7, 6],
        [7, 8, 5, 2, 6]],

       [[4, 3, 6, 5, 7],
        [3, 5, 3, 7, 8],
        [6, 7, 8, 8, 7],
        [2, 1, 3, 7, 4],
        [3, 2, 2, 5, 1]]])

In [66]:
np.random.rand(5)

array([0.50231634, 0.92103208, 0.82043147, 0.21211001, 0.74599279])